name: tf2
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.8
  - ipython=7.28
  - ipywidgets=7.6
  - joblib=0.14
  - jupyter=1.0
  - matplotlib=3.4
  - nbdime=3.1
  - nltk=3.6
  - numexpr=2.7
  - numpy=1.19
  - opencv=4.5
  - pandas=1.3
  - pillow=8.3
  - pyglet=1.5
  - pyopengl=3.1
  - python-graphviz
  - requests=2.26
  - scikit-learn=1.0
  - scipy=1.7
  - tqdm=4.62
  - widgetsnbextension=3.5
  - graphviz
  - ftfy=6.0
  - ipykernel
  - pip
  - pip:
      # Apple Silicon TF stack for Python 3.8
      - tensorflow-macos==2.9.2
      - tensorflow-metal==0.5.1
      - tensorflow-addons==0.17.1
      - tensorflow-datasets==4.6.0
      - tensorflow-hub==0.12.0
      - tensorflow-probability==0.17.0
      # xgboost for 3.8
      - xgboost==1.7.6
      # leave these out on mac arm or upgrade later only if you truly need them
      # - tf-agents==0.12.0
      # - tfx
      # - tensorflow-serving-api
      # - gym[atari,accept-rom-license]~=0.21.0
  - attrs=20.3
  - click=7.1
  - packaging=20.9
  - six=1.15
  - typing-extensions=3.7
